# ML-10 — Content Action Playbook

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/suha-2004/flyrank-ml-internship/blob/main/work/notebooks/w07_action_playbook.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [1]:
!git clone https://github.com/suha-2004/flyrank-ml-internship.git

Cloning into 'flyrank-ml-internship'...
remote: Enumerating objects: 219, done.
remote: Counting objects: 100% (219/219), done.
remote: Compressing objects: 100% (173/173), done.
remote: Total 219 (delta 104), reused 102 (delta 29), pack-reused 0 (from 0)
Receiving objects: 100% (219/219), 3.07 MiB | 12.46 MiB/s, done.
Resolving deltas: 100% (104/104), done.

In [2]:
%cd flyrank-ml-internship

/content/flyrank-ml-internship

In [3]:
import pandas as pd
import numpy as np

print("Repository loaded.")

Repository loaded.

In [4]:
import os

print("Current folder:")
print(os.getcwd())

print("\nFolders/files here:")
print(os.listdir("."))

Current folder:
/content/flyrank-ml-internship

Folders/files here:
['scripts', 'requirements.txt', 'data', 'GUIDE.md', 'work', 'paper', '.github', 'AGENTS.md', 'outputs', 'CLAUDE.md', 'README.md', 'LICENSE', 'submission', '.git', '.gitignore', 'notebooks', 'DATA_USE.md', 'docs', 'SETUP.md', 'skills']

In [5]:
import os

for root, dirs, files in os.walk("."):
    for file in files:
        if file == "capstone_ranked_recommendations.csv":
            print("FOUND:", os.path.join(root, file))

In [6]:
print(os.listdir("./outputs"))

['charts', 'refresh_queue_sample.csv', 'model_report.md']

In [7]:
print(os.listdir("./work"))

['capstone_report_template.md', 'README.md', 'notebooks']

In [8]:
import os

matches = []

for root, dirs, files in os.walk("/content"):
    for file in files:
        if file == "capstone_ranked_recommendations.csv":
            matches.append(os.path.join(root, file))

print("Found files:")
for path in matches:
    print(path)

Found files:

In [9]:
import pandas as pd

recommendations = pd.read_csv("./outputs/refresh_queue_sample.csv")

print("Shape:", recommendations.shape)
print("Columns:")
print(recommendations.columns.tolist())

recommendations.head()

Shape: (200, 28)
Columns:
['final_rank', 'content_id', 'client_id', 'final_refresh_score', 'best_model_name', 'best_model_probability', 'baseline_refresh_score', 'confidence', 'suggested_action', 'final_reason_codes', 'is_declining_label', 'impressions_90d', 'clicks_90d', 'sessions_90d', 'avg_position', 'ctr', 'content_age_days', 'days_since_last_update', 'word_count', 'trend_direction', 'competition_level', 'content_type', 'main_intent', 'age_tier', 'freshness_tier', 'word_count_tier', 'impression_tier', 'position_tier']

,final_rank,content_id,client_id,final_refresh_score,best_model_name,best_model_probability,baseline_refresh_score,confidence,suggested_action,final_reason_codes,...,word_count,trend_direction,competition_level,content_type,main_intent,age_tier,freshness_tier,word_count_tier,impression_tier,position_tier
0,1,content_1f080331fa2b,client_3fdba35f04,81.636697,random_forest,0.782079,0.844481,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...,...,1404.0,down,MEDIUM,keyword article,informational,91-180,91-180,1000-2000,good,page_1
1,2,content_6aa43079fb0c,client_3fdba35f04,81.447656,random_forest,0.788105,0.825477,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1457.0,down,LOW,keyword article,informational,91-180,91-180,1000-2000,good,page_1
2,3,content_d6570c51c9bd,client_3fdba35f04,81.430346,random_forest,0.847372,0.695884,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1362.0,down,MEDIUM,keyword article,informational,91-180,91-180,1000-2000,moderate,striking
3,4,content_72e800a9c214,client_3fdba35f04,81.034960,random_forest,0.774371,0.842545,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1371.0,down,MEDIUM,keyword article,commercial,91-180,91-180,1000-2000,good,page_1
4,5,content_e04eb9549989,client_3fdba35f04,80.873188,random_forest,0.814805,0.749468,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1408.0,down,LOW,keyword article,informational,91-180,91-180,1000-2000,good,page_1

## 1. Ranked actions + reason codes

*The queue: what to do first, and why, in words a human trusts.*
### Ranked action queue

The action queue ranks content using the final refresh score. Higher-ranked items receive higher priority for human review.

Each recommendation includes reason codes and a suggested action so that the content team can understand why an item was prioritized.

The queue is intended to support human decision-making rather than automatically change content.

In [10]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
# Create the W07 action queue from the existing project output

action_queue = recommendations[
    [
        "final_rank",
        "content_id",
        "final_refresh_score",
        "confidence",
        "suggested_action",
        "final_reason_codes"
    ]
].copy()

print("Action queue shape:", action_queue.shape)

action_queue.head(10)

Action queue shape: (200, 6)

,final_rank,content_id,final_refresh_score,confidence,suggested_action,final_reason_codes
0,1,content_1f080331fa2b,81.636697,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...
1,2,content_6aa43079fb0c,81.447656,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...
2,3,content_d6570c51c9bd,81.430346,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...
3,4,content_72e800a9c214,81.034960,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...
4,5,content_e04eb9549989,80.873188,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...
5,6,content_b69288c5e701,80.754770,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...
6,7,content_9b6df29f7889,80.632923,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...
7,8,content_bb6ebb5ec8c8,80.371236,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...
8,9,content_4d76cdb3387b,80.362748,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...
9,10,content_b4f35d640b1c,80.321757,medium,refresh,declining_with_demand|model_decline_risk|visib...

In [11]:
# Check that the queue is ordered by final rank

print("First 10 ranked recommendations:")
print(
    action_queue[
        [
            "final_rank",
            "final_refresh_score",
            "confidence",
            "suggested_action"
        ]
    ].head(10)
)

First 10 ranked recommendations:
   final_rank  final_refresh_score confidence        suggested_action
0           1            81.636697       high  refresh_and_review_ctr
1           2            81.447656       high  refresh_and_review_ctr
2           3            81.430346     medium  refresh_and_review_ctr
3           4            81.034960       high  refresh_and_review_ctr
4           5            80.873188     medium  refresh_and_review_ctr
5           6            80.754770       high  refresh_and_review_ctr
6           7            80.632923       high  refresh_and_review_ctr
7           8            80.371236       high  refresh_and_review_ctr
8           9            80.362748     medium  refresh_and_review_ctr
9          10            80.321757     medium                 refresh

## 2. Intended use and limits

*Who uses this, for what — and where it stops being valid.*
### Intended use

The playbook is intended for content and search teams to prioritize pages for human review. It uses the observed model score, confidence, reason codes, and content signals to identify pages that may deserve attention.

The recommendations are decision-support and are not guaranteed predictions of future search performance.

### Limits

A high refresh score does not prove that changing a page will improve search performance. The model identifies patterns in the available historical data but does not establish causation.

The recommendations may become less reliable if the underlying search environment, content mix, or data distribution changes substantially.

In [12]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 3. Human review + the no-go list

*What a person must check before acting. What should never be automated.*
### Human review

Before acting on a recommendation, a content reviewer should check the page's current content, search intent, recent changes, ranking context, and business relevance.

The reviewer should confirm that the reason codes make sense for the specific page before making a content decision.

### No-go list

The model should not automatically rewrite, delete, publish, or redirect content based only on its score.

The recommendation should not replace editorial judgment, search-quality review, or human approval.

In [13]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
print("Human review required: YES")
print("Automatic rewriting: NO")
print("Automatic deletion: NO")
print("Automatic publishing: NO")
print("Automatic redirecting: NO")

Human review required: YES
Automatic rewriting: NO
Automatic deletion: NO
Automatic publishing: NO
Automatic redirecting: NO

## 4. Monitoring / retrain triggers

*What would tell you the recommendations went stale?*
### Monitoring and retraining

The recommendation system should be monitored for changes in model performance, feature distributions, recommendation patterns, and search behavior.

A review or retraining cycle should be considered when validation performance declines materially, important feature distributions change substantially, or the search environment and content strategy change enough that historical patterns may no longer represent current behavior.

In [14]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
print("Number of recommendations:", len(recommendations))

print("\nConfidence distribution:")
print(recommendations["confidence"].value_counts())

print("\nSuggested action distribution:")
print(recommendations["suggested_action"].value_counts())

Number of recommendations: 200

Confidence distribution:
confidence
high      161
medium     39
Name: count, dtype: int64

Suggested action distribution:
suggested_action
refresh_and_review_ctr           130
refresh                           35
refresh_and_review_engagement     35
Name: count, dtype: int64

## 5. Exports for the paper

*Write the queue (and any figures you want to reuse) to work/outputs/ — your paper builds on these files.*
### Paper exports

The ranked action queue is exported to `work/outputs/` so that the research paper can reference a reproducible recommendation output.

The export contains the ranking, refresh score, confidence level, suggested action, and reason codes.

In [15]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
import os

os.makedirs("./work/outputs", exist_ok=True)

output_path = "./work/outputs/capstone_action_playbook.csv"

action_queue.to_csv(
    output_path,
    index=False
)

print("Saved:", output_path)
print("Rows:", len(action_queue))

Saved: ./work/outputs/capstone_action_playbook.csv
Rows: 200

In [16]:
paper_preview = action_queue.head(20).copy()

paper_preview

,final_rank,content_id,final_refresh_score,confidence,suggested_action,final_reason_codes
0,1,content_1f080331fa2b,81.636697,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...
1,2,content_6aa43079fb0c,81.447656,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...
2,3,content_d6570c51c9bd,81.430346,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...
3,4,content_72e800a9c214,81.034960,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...
4,5,content_e04eb9549989,80.873188,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...
5,6,content_b69288c5e701,80.754770,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...
6,7,content_9b6df29f7889,80.632923,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...
7,8,content_bb6ebb5ec8c8,80.371236,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...
8,9,content_4d76cdb3387b,80.362748,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...
9,10,content_b4f35d640b1c,80.321757,medium,refresh,declining_with_demand|model_decline_risk|visib...
10,11,content_ba6f9dfcbca1,80.282275,medium,refresh,declining_with_demand|model_decline_risk|visib...
11,12,content_1b51115391a3,80.134145,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...
12,13,content_e76ac7fed711,80.062755,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...
13,14,content_b1d593faf9c6,79.957743,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...
14,15,content_20ddbdfbbd90,79.878200,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...
15,16,content_73b70737ee63,79.875242,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...
16,17,content_81e59177b59a,79.601277,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...
17,18,content_91fefd1726b3,79.562384,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...
18,19,content_aa76dcfed6e7,79.557090,high,refresh_and_review_engagement,declining_with_demand|low_engagement_visible_p...
19,20,content_03475a5923fe,79.539037,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...

In [17]:
print("ML-10 SELF-CHECK")
print("================")

print("Recommendation dataset loaded:", True)
print("Action queue created:", True)
print("Rows in action queue:", len(action_queue))
print("Human review required:", True)
print("Automatic actions prohibited:", True)
print("Paper export created:", os.path.exists(output_path))

ML-10 SELF-CHECK
================
Recommendation dataset loaded: True
Action queue created: True
Rows in action queue: 200
Human review required: True
Automatic actions prohibited: True
Paper export created: True

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.